-- Generated by Drydock from this repository's own migrations. Review before
-- applying: it was written without reading your database.
--
-- `avatar_interactions` is readable by the anonymous key according to the committed
-- schema. The predicate below is copied from a policy this repository already
-- uses for a table scoped the same way, so it follows the authorisation model
-- already in place rather than inventing one.

alter table public.avatar_interactions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'avatar_interactions'
      and cmd in ('SELECT', 'ALL')
  ) then
    create policy "avatar_interactions_select_scoped" on public.avatar_interactions
      for select using (EXISTS ( SELECT 1 FROM matches m WHERE ( (m.id = avatar_interactions.match_id) AND ((select auth.uid()) IN ( SELECT founder_profiles.user_id FROM founder_profiles WHERE (founder_profiles.id = ANY (ARRAY[m.founder1_id, m.founder2_id])) )) ) ));
  end if;
end
$$;
